---
title: "Code extract water charges authorization files"
author: "Beatriz Couto Ribeiro"
date: "2025-01-07"
output: html_document
editor_options: 
  chunk_output_type: console
---


# Load Packages
```{r setup, include=FALSE}

rm(list=ls())


if (!require("pacman")) install.packages("pacman") #pacman will not accept a character vector so the same packages are repeated

pacman::p_load(tidyverse, #packages for data science
               plm, #estimation of linear panel models
               ggplot2,  #creating graphics
               devtools, #web developer tools 
               rmarkdown, #reproducibility
               tidyr,  #changing the shape and hierarchy of a data set
               dplyr, #grammar of data manipulation
               Synth, #importing and exporting
               SCtools, #extensions for Synthetic Controls Analysis
               panelView, #visualize data panels
               httr, # call url
               jsonlite, # use API
               ggrepel, #labels with ggplot
               ggthemes, #different graph themes for ggplot
               ggpubr, #put figures together
               rvest,
               htmltools,
               readtext,
               readr,
               pdftools,
               stringr,
               data.table, 
               tabulapdf,
               stringdist,
               openxlsx,
               readxl,
               tesseract,
               tm, #text mining package
               stringi, #remove accents from foreigner languages
               magick,
               rJava) # Fast aggregation of large data

# Youtube Video to Change Java's version and install the package: https://www.youtube.com/watch?v=nlsWjezvsg8&t=428s
# library(tabulizer)
# 
# remotes::install_github(c("ropensci/tabulizerjars", "ropensci/tabulizer"), INSTALL_opts = "--no-multiarch")
# 
# remotes::install_github(c("ropensci/tabulapdf"))

#install_version("tm", version = "0.7-15", repos = "http://cran.us.r-project.org")


```


# Set Folder 
```{r}

# Define the folder containing the PDF files
pdf_folder <- "C:/Users/wb618493/OneDrive - WBG/Documents/Piaui - DPL/Cobranca de Agua/water_charges_pi_data_04-01-2025"

```

# Check all the pdf on the file 
```{r}

# List all PDF files (using a case-insensitive pattern)
files <- list.files(pdf_folder, pattern = "\\.pdf$", ignore.case = TRUE)

# Create the full paths for the PDF files
full_paths <- file.path(pdf_folder, files)

# Read the text from each PDF
data <- lapply(full_paths, pdf_text)

# length of each vector corresponds to the number of pages in the PDF file
lapply(data, length) 

# Inspect the result
print(data)

```


# Extraction of the improtant parts in the file: process type, date, city, river basin...
```{r}

# List all PDF files (using a case-insensitive pattern)
files <- list.files(pdf_folder, pattern = "\\.pdf$", ignore.case = TRUE)

# List all PDF files (using a case-insensitive pattern)
files <- list.files(pdf_folder, pattern = "\\.pdf$", ignore.case = TRUE)

# Create the full paths for the PDF files
full_paths <- file.path(pdf_folder, files)

# Read the text from each PDF
pdf_texts <- lapply(full_paths, pdf_text)

# Function to clean and extract the required information from the PDF text
extract_info <- function(pdf_text, file_name) {
  # Concatenate all the pages into a single string
  text <- paste(pdf_text, collapse = " ")
  
  # Clean the text by removing unwanted characters like "\n" and extra spaces
  text_clean <- gsub("\n", " ", text)  # Replace newlines with a space
  text_clean <- gsub("\\s+", " ", text_clean)  # Replace multiple spaces with a single space
  text_clean <- trimws(text_clean)  # Trim leading and trailing spaces
  
  # Remove accents from foreign characters
  text_clean <- stri_trans_general(text_clean, "Latin-ASCII")  # Remove accents using stringi
  
  # Check if cleaning is working, print part of cleaned text
  #print(substr(text_clean, 1, 1000))  # Uncomment to inspect cleaned text (first 200 characters)
  
  # Extract the characters following "AUTPOOP." (12 characters in the format XXXXX-XX/YYYY)
  autpoop_match <- str_extract(text_clean, "(AUTPOOP\\.\\s*|ACSPROOU\\.\\s*|AUTPOOU\\.\\s*|PI-CPA\\.\\s*|PI-RAODU\\.\\s*|PI-ODRH\\.\\s*|PI-AODU\\.\\s*|PI-AODU\\.\\s*|PI-OP\\.\\s*|PI-RODRH\\.\\s*|PI-ROP\\.\\s*)(\\d{5}-\\d{1}/\\d{4})")
  
  # Extract the date following "VALIDADE:" (next 10 characters in the format DD/MM/YYYY)
  validade_match <- str_extract(text_clean, "VALIDADE:\\s*(\\d{2}/\\d{2}/\\d{4})")
  
  # Extract the 7 words following "CAPTAÇÃO"
  categoria_match <- str_extract(text_clean, "CAPTACAO\\s*([a-zA-Z]+(?:\\s+[a-zA-Z]+){0,6})")
  
  # Extract the 7 words following "EMPREENDIMENTO"
  empreendimento_match <- str_extract(text_clean, "EMPREENDIMENTO\\s*([a-zA-Z]+(?:\\s+[a-zA-Z]+){0,5})")
  
  # Extract the 7 words following "cidade"
  city_match <- str_extract(text_clean, "Coordenadas Geograficas:\\s*([a-zA-Z]+(?:\\s+[a-zA-Z]+){0,3})")
  
  # Extract the 7 words following "fonte"
  water_source_match <- str_extract(text_clean, "BACIA\\s*([a-zA-Z]+(?:\\s+[a-zA-Z]+){0,5})")
  
  # Extract the 7 words following "FINALIDADE(S)"
  use_match <- str_extract(text_clean, "FINALIDADE(S)?\\s*((\\S+\\s*){1,6})")
  
  # Remove unwanted words
  use_match <- gsub("\\b(FINALIDADE\\(S\\)|Assinado|eletronicamente|por)\\b", "", use_match)
  use_match <- trimws(use_match)  # Trim leading/trailing spaces after removal
  
  # Extract the values after "Janeiro", which could be numbers like "5,00", "8,0", etc.
  amount_match <- str_extract(text_clean, "Volume Anual \\(m³\\):\\s*([\\d,.]+)")
  
  # Remove unwanted words from the extracted values
  validade_match <- gsub("VALIDADE:\\s*", "", validade_match)
  empreendimento_match <- gsub("EMPREENDIMENTO\\s*", "", empreendimento_match)
  empreendimento_match <- gsub("Municipio\\s*", "", empreendimento_match)
  #use_match <- gsub("FINALIDADE(S)?\\s*", "", use_match)
  city_match <- gsub("Coordenadas Geograficas:\\s*", "", city_match)
  amount_match <- gsub("Volume Anual \\(m³\\):\\s*", "", amount_match)
  
  # Return a list of the extracted values, including the file name as "ID"
  return(list(
    ID = file_name,
    autpoop = autpoop_match,
    validade = validade_match,
    categoria = categoria_match,
    empreendimento = empreendimento_match,
    cidade = city_match,
    fonte = water_source_match,
    uso = use_match, 
    volume = amount_match
  ))
}

# Apply the function to each PDF text and extract the information
extracted_info <- mapply(extract_info, pdf_texts, files, SIMPLIFY = FALSE)

# View the extracted information
extracted_info

```


# Harmonize columns format
```{r}

# Convert the list of extracted information into a data frame
extracted_df <- do.call(rbind, lapply(extracted_info, function(x) as.data.frame(t(unlist(x)), stringsAsFactors = FALSE)))

# Name the columns of the data frame
colnames(extracted_df) <- c("ID", "processo", "validade", "categoria", "empreendimento", "cidade", "fonte", "uso", "volume")


```


# Cleanning database
```{r}

# Create the 'tipo' column by extracting the part before the dot in 'processo'
extracted_df$tipo <- sub("\\..*", "", extracted_df$processo)

# Create the 'ano' column by extracting the first four digits from 'processo'
extracted_df$ano <- substr(extracted_df$processo, nchar(extracted_df$processo) - 3, nchar(extracted_df$processo))

# Replace commas with dots in the specified columns
columns_to_replace <- c("volume")
extracted_df[columns_to_replace] <- lapply(extracted_df[columns_to_replace], function(x) gsub(",", ".", x))


# Create the new 'uso_detalhe' column based on 'tipo' column values
extracted_df <- extracted_df %>%
  mutate(uso_detalhe = case_when(
    tipo == "ACSPROOU" ~ "DESPACHO CONCLUSIVO ARQUIVAMENTO, CANCELAMENTO OU SUSPENSÃO DE PROCESSO DE AUTORIZAÇÃO OU OUTORGA DE USO DA ÁGUA",
    tipo == "AUTPOOP" ~ "AUTORIZAÇÃO PARA PERFURAÇÃO DE POÇO TUBULAR E OUTORGA PREVENTIVA",
    tipo == "AUTPOOU" ~ "REGULARIZAÇÃO DE POÇO TUBULAR",
    tipo == "PI-AODU" ~ "AUTORIZAÇÃO E OUTORGA DE DIREITO DE USO",
    tipo == "PI-CPA" ~ "DESPACHO CONCLUSIVO - CONSULTA PRÉVIA - USO ÁGUA",
    tipo == "PI-ODRH" ~ "OUTORGA DE DIREITO DE USO",
    tipo == "PI-OP" ~ "OUTORGA PREVENTIVA",
    tipo == "PI-RAODU" ~ "RENOVAÇÃO DE AUTORIZAÇÃO E DE OUTORGA DE DIREITO DE USO",
    tipo == "PI-RODRH" ~ "RENOVAÇÃO DE OUTORGA DE DIREITO DE USO",
    tipo == "PI-ROP" ~ "RENOVAÇÃO DE OUTORGA PREVENTIVA",
    TRUE ~ NA_character_  # Default case, in case 'tipo' is not recognized
  ))

# Define the list of values to replace
unwanted_values <- c(
  "CAPTACAO SUPERFICIAL EM CURSO D",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO ACQUABRASILIS CULTIVO E",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO ACUDE DO CRISPIM",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO ACUDE DO PREFEITO",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO ACUDE UNIAO",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO BARRAGEM ALGODOES II",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO BARRAGEM NOVA FORTALEZA",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO BARRAGEM PEDRA REDONDA",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO CAPTACAO SUPERFICIAL",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO CAPTACAO SUPERFICIAL BARRAGEM",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO ESTRUTURA FLUTUANTE",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO FAZENDA BROTO Municipio",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO INCLUSAO DE VEICULO",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO OUTORGA BARRAGEM PEDREGULHOS",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO PROJETO ADUTORA PREF",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO REFORMA E AMPLIACAO",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO RENOVACAO DA OUTORGA",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO SAA FARTURA E",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO SANTA RITA DATA",
  "CAPTACAO SUPERFICIAL EM RESERVATORIO EMPREENDIMENTO SISTEMA DE ABASTECIMENTO"
)

# Replace values in the 'categoria' column
extracted_df$categoria[extracted_df$categoria %in% unwanted_values] <- "CAPTACAO SUPERFICIAL"

# Define the mapping of old values to new values
uso_replacements <- c(
  "FINALIDADE(S) ABASTECIMENTO PUBLICO (principal)" = "ABASTECIMENTO PUBLICO",
  "FINALIDADE(S) ABASTECIMENTO PUBLICO (principal) / IRRIGACAO" = "ABASTECIMENTO PUBLICO / IRRIGACAO",
  "FINALIDADE(S) ABASTECIMENTO PUBLICO (principal) / OBRAS" = "ABASTECIMENTO PUBLICO / OBRAS",
  "FINALIDADE(S) ABASTECIMENTO PUBLICO (principal) DEMANDA RESERVADA" = "ABASTECIMENTO PUBLICO / DEMANDA RESERVADA",
  "FINALIDADE(S) ABASTECIMENTO PUBLICO (principal) Emitido" = "ABASTECIMENTO PUBLICO",
  "FINALIDADE(S) ABASTECIMENTO PUBLICO / CONSUMO HUMANO" = "ABASTECIMENTO PUBLICO / CONSUMO HUMANO",
  "FINALIDADE(S) ABASTECIMENTO PUBLICO / SERVICOS (RECREACAO," = "ABASTECIMENTO PUBLICO / SERVICOS",
  "FINALIDADE(S) AQUICULTURA EM TANQUE ESCAVADO (principal)" = "AQUICULTURA EM TANQUE ESCAVADO",
  "FINALIDADE(S) AQUICULTURA EM TANQUE ESCAVADO /" = "AQUICULTURA EM TANQUE ESCAVADO",
  "FINALIDADE(S) COMBATE A INCENDIO (principal)" = "COMBATE A INCENDIO",
  "FINALIDADE(S) COMBATE A INCENDIO (principal) /" = "COMBATE A INCENDIO",
  "FINALIDADE(S) COMBATE A INCENDIO / OUTRA" = "COMBATE A INCENDIO",
  "FINALIDADE(S) CONSTRUCAO CIVIL" = "CONSTRUCAO CIVIL",
  "FINALIDADE(S) CONSTRUCAO CIVIL (principal)" = "CONSTRUCAO CIVIL",
  "FINALIDADE(S) CONSUMO HUMANO DOMICILIAR (principal)" = "CONSUMO HUMANO DOMICILIAR",
  "FINALIDADE(S) CONSUMO HUMANO DOMICILIAR (principal) /" = "CONSUMO HUMANO DOMICILIAR",
  "FINALIDADE(S) CONSUMO HUMANO DOMICILIAR / ABASTECIMENTO" = "CONSUMO HUMANO DOMICILIAR / ABASTECIMENTO",
  "FINALIDADE(S) CONSUMO HUMANO DOMICILIAR / AQUICULTURA" = "CONSUMO HUMANO DOMICILIAR / AQUICULTURA",
  "FINALIDADE(S) CONSUMO HUMANO DOMICILIAR / CONSTRUCAO" = "CONSUMO HUMANO DOMICILIAR / CONSTRUCAO",
  "FINALIDADE(S) CONSUMO HUMANO DOMICILIAR / CRIACAO" = "CONSUMO HUMANO DOMICILIAR / CRIACAO",
  "FINALIDADE(S) CONSUMO HUMANO DOMICILIAR / INDUSTRIA" = "CONSUMO HUMANO DOMICILIAR / INDUSTRIA",
  "FINALIDADE(S) CONSUMO HUMANO DOMICILIAR / IRRIGACAO" = "CONSUMO HUMANO DOMICILIAR / IRRIGACAO",
  "FINALIDADE(S) CONSUMO HUMANO DOMICILIAR / MINERACAO" = "CONSUMO HUMANO DOMICILIAR / MINERACAO",
  "FINALIDADE(S) CONSUMO HUMANO DOMICILIAR / OUTRA" = "CONSUMO HUMANO DOMICILIAR / OUTRA",
  "FINALIDADE(S) CONSUMO HUMANO DOMICILIAR / SERVICOS" = "CONSUMO HUMANO DOMICILIAR / SERVICOS",
  "FINALIDADE(S) CRIACAO ANIMAL (principal)" = "CRIACAO ANIMAL",
  "FINALIDADE(S) CRIACAO ANIMAL (principal) / IRRIGACAO" = "CRIACAO ANIMAL / IRRIGACAO",
  "FINALIDADE(S) CRIACAO ANIMAL (principal) / OUTRA" = "CRIACAO ANIMAL / OUTRA",
  "FINALIDADE(S) CRIACAO ANIMAL / CONSUMO HUMANO" = "CRIACAO ANIMAL / CONSUMO HUMANO",
  "FINALIDADE(S) CRIACAO ANIMAL / IRRIGACAO (principal)" = "CRIACAO ANIMAL / IRRIGACAO",
  "FINALIDADE(S) CRIACAO ANIMAL / OUTRA FINALIDADE" = "CRIACAO ANIMAL / IRRIGACAO",
  "FINALIDADE(S) INDUSTRIA    ERYSON" = "INDUSTRIA",
  "FINALIDADE(S) INDUSTRIA    FANUEL" = "INDUSTRIA",
  "FINALIDADE(S) INDUSTRIA    LAYSSA" = "INDUSTRIA",
  "FINALIDADE(S) INDUSTRIA (principal)" = "INDUSTRIA",
  "FINALIDADE(S) INDUSTRIA (principal) / CONSTRUCAO CIVIL" = "INDUSTRIA / CONSTRUCAO CIVIL",
  "FINALIDADE(S) INDUSTRIA (principal) / MINERACAO -" = "INDUSTRIA / MINERACAO",
  "FINALIDADE(S) INDUSTRIA (principal) / OBRAS HIDRAULICAS" = "INDUSTRIA  / OBRAS HIDRAULICAS",
  "FINALIDADE(S) INDUSTRIA (principal) / OUTRA FINALIDADE" = "INDUSTRIA  / OUTRA FINALIDADE",
  "FINALIDADE(S) INDUSTRIA (principal) / SERVICOS (RECREACAO," = "INDUSTRIA / SERVICOS",
  "FINALIDADE(S) INDUSTRIA / CONSTRUCAO CIVIL (principal)" = "INDUSTRIA / CONSTRUCAO CIVIL",
  "FINALIDADE(S) IRRIGACAO (principal)" = "IRRIGACAO",
  "FINALIDADE(S) IRRIGACAO (principal) / OBRAS HIDRAULICAS" = "IRRIGACAO / OBRAS HIDRAULICAS",
  "FINALIDADE(S) IRRIGACAO / COMBATE A INCENDIO" = "IRRIGACAO / COMBATE A INCENDIO",
  "FINALIDADE(S) IRRIGACAO / OUTRA FINALIDADE (USO" = "IRRIGACAO / OUTRA FINALIDADE",
  "FINALIDADE(S) IRRIGACAO / SERVICOS (RECREACAO, ESPORTE," = "IRRIGACAO / SERVICOS",
  "FINALIDADE(S) MINERACAO - OUTROS PROCESSOS EXTRATIVOS" = "MINERACAO",
  "FINALIDADE(S) OBRAS HIDRAULICAS (principal)" = "OBRAS HIDRAULICAS",
  "FINALIDADE(S) OUTRA FINALIDADE (USO CONSUNTIVO) (principal)" = "OUTRA FINALIDADE (USO CONSUNTIVO)",
  "FINALIDADE(S) OUTRA FINALIDADE (USO CONSUNTIVO) /" = "OUTRA FINALIDADE (USO CONSUNTIVO)",
  "FINALIDADE(S) SERVICOS (RECREACAO, ESPORTE, TURISMO, PAISAGISMO;" = "SERVICOS",
  "FINALIDADE(S) DILUICAO DE EFLUENTES (principal)" = "DILUICAO DE EFLUENTES",
  "FINALIDADE(S) ESGOTAMENTO SANITARIO (principal) / DILUICAO" = "ESGOTAMENTO SANITARIO / DILUICAO DE EFLUENTES",
  "FINALIDADE(S) ESGOTAMENTO SANITARIO / DILUICAO DE" = "ESGOTAMENTO SANITARIO / DILUICAO DE EFLUENTES"
)

# Use dplyr::recode to apply the replacements
extracted_df$uso <- uso_replacements[match(extracted_df$uso, names(uso_replacements))]


# Create the new 'uso_principal' column based on 'uso' column values
extracted_df <- extracted_df %>%
  mutate(uso_principal = case_when(
    # Public Supply
    uso == "ABASTECIMENTO PUBLICO / CONSUMO HUMANO" ~ "ABASTECIMENTO PUBLICO",
    uso == "ABASTECIMENTO PUBLICO / DEMANDA RESERVADA" ~ "ABASTECIMENTO PUBLICO",
    uso == "ABASTECIMENTO PUBLICO / IRRIGACAO" ~ "ABASTECIMENTO PUBLICO",
    uso == "ABASTECIMENTO PUBLICO / OBRAS" ~ "ABASTECIMENTO PUBLICO",
    uso == "ABASTECIMENTO PUBLICO / SERVICOS" ~ "ABASTECIMENTO PUBLICO",
    
    # Aquaculture
    uso == "AQUICULTURA EM TANQUE ESCAVADO" ~ "AQUICULTURA",
    
    # Firefighting
    uso == "COMBATE A INCENDIO" ~ "COMBATE A INCENDIO",
    
    # Civil Construction
    uso == "CONSTRUCAO CIVIL" ~ "CONSTRUCAO CIVIL",
    
    # Domestic Human Consumption
    uso == "CONSUMO HUMANO DOMICILIAR / ABASTECIMENTO" ~ "CONSUMO HUMANO DOMICILIAR",
    uso == "CONSUMO HUMANO DOMICILIAR / AQUICULTURA" ~ "CONSUMO HUMANO DOMICILIAR",
    uso == "CONSUMO HUMANO DOMICILIAR / CONSTRUCAO" ~ "CONSUMO HUMANO DOMICILIAR",
    uso == "CONSUMO HUMANO DOMICILIAR / CRIACAO" ~ "CONSUMO HUMANO DOMICILIAR",
    uso == "CONSUMO HUMANO DOMICILIAR / INDUSTRIA" ~ "CONSUMO HUMANO DOMICILIAR",
    uso == "CONSUMO HUMANO DOMICILIAR / IRRIGACAO" ~ "CONSUMO HUMANO DOMICILIAR",
    uso == "CONSUMO HUMANO DOMICILIAR / MINERACAO" ~ "CONSUMO HUMANO DOMICILIAR",
    uso == "CONSUMO HUMANO DOMICILIAR / OUTRA" ~ "CONSUMO HUMANO DOMICILIAR",
    uso == "CONSUMO HUMANO DOMICILIAR / SERVICOS" ~ "CONSUMO HUMANO DOMICILIAR",
    
    # Animal Husbandry
    uso == "CRIACAO ANIMAL / CONSUMO HUMANO" ~ "CRIACAO ANIMAL",
    uso == "CRIACAO ANIMAL / IRRIGACAO" ~ "CRIACAO ANIMAL",
    uso == "CRIACAO ANIMAL / OUTRA" ~ "CRIACAO ANIMAL",
    
    # Sanitation
    uso == "ESGOTAMENTO SANITARIO / DILUICAO DE EFLUENTES" ~ "ESGOTAMENTO SANITARIO",
    
    # Industry
    uso == "INDUSTRIA  / OBRAS HIDRAULICAS" ~ "INDUSTRIA",
    uso == "INDUSTRIA  / OUTRA FINALIDADE" ~ "INDUSTRIA",
    uso == "INDUSTRIA / CONSTRUCAO CIVIL" ~ "INDUSTRIA",
    uso == "INDUSTRIA / MINERACAO" ~ "INDUSTRIA",
    uso == "INDUSTRIA / SERVICOS (RECREACAO" ~ "INDUSTRIA",
    
    # Irrigation
    uso == "IRRIGACAO / COMBATE A INCENDIO" ~ "IRRIGACAO",
    uso == "IRRIGACAO / OBRAS HIDRAULICAS" ~ "IRRIGACAO",
    uso == "IRRIGACAO / OUTRA FINALIDADE" ~ "IRRIGACAO",
    uso == "IRRIGACAO / SERVICOS" ~ "IRRIGACAO",
    
    # Default case
    TRUE ~ uso
  ))

# Exclude all words after the word "Aquifero"
extracted_df$fonte <- str_replace(extracted_df$fonte, "\\sAquifero.*", "")
extracted_df$fonte <- str_replace(extracted_df$fonte, "\\sMorro.*", "")
extracted_df$fonte <- str_replace(extracted_df$fonte, "\\sGrande.*", "")
extracted_df$fonte <- str_replace(extracted_df$fonte, "\\sBons.*", "")
extracted_df$fonte <- str_replace(extracted_df$fonte, "\\sFINALIDADE.*", "")
extracted_df$fonte <- str_replace(extracted_df$fonte, "\\sAssinado eletronicamente por.*", "")
extracted_df$fonte <- str_replace(extracted_df$fonte, "\\sSem Denominacao.*", "")


# Create the new 'uso_principal' column based on 'uso' column values
extracted_df <- extracted_df %>%
  mutate(fonte_principal = case_when(
    # Public Supply
    fonte == "BACIA DO CANINDE"  ~ "BACIA DO CANINDE",
    fonte == "BACIAS DIFUSAS DO ALTO PARNAIBA E"  ~ "BACIAS DIFUSAS DO ALTO PARNAIBA",
fonte == "BACIA DO POTI"  ~ "BACIA DO POTI",
fonte == "BACIA DO GURGUEIA"  ~ "BACIA DO GURGUEIA",
fonte == "BACIAS DIFUSAS DO BAIXO PARNAIBA"  ~ "BACIAS DIFUSAS DO BAIXO PARNAIBA",
fonte == "BACIAS DIFUSAS DO BAIXO PARNAIBA"  ~ "BACIAS DIFUSAS DO BAIXO PARNAIBA",
fonte == "BACIA DO ITAUEIRA"  ~ "BACIA DO ITAUEIRA",
fonte == "BACIAS DIFUSAS DO MEDIO PARNAIBA"  ~ "BACIAS DIFUSAS DO MEDIO PARNAIBA",
fonte == "BACIA DO LONGA"  ~ "BACIA DO LONGA",
fonte == "BACIA DO PIRANJI"  ~ "BACIA DO PIRANJI",
fonte == "BACIA DO LONGA Piaui"  ~ "BACIA DO LONGA",
fonte == "BACIA DO POTI DE NATAL"  ~ "BACIA DO POTI",
fonte == "BACIAS DIFUSAS DA BARRAGEM DE BOA"  ~ "BACIAS DIFUSAS DA BARRAGEM DE BOA ESPERANCA",
fonte == "BACIA DO CANINDE COMPRIDA"  ~ "BACIA DO CANINDE",
fonte == "BACIAS DIFUSAS DO LITORAL"  ~ "BACIAS DIFUSAS DO LITORAL",
fonte == "BACIA DO POTI Juriti JURITI"  ~ "BACIA DO POTI",
fonte == "BACIA DO GURGUEIA Aluvionar"  ~ "BACIA DO GURGUEIA",
fonte == "BACIAS DIFUSAS DO BAIXO PARNAIBA Rio"  ~ "BACIAS DIFUSAS DO BAIXO PARNAIBA",
fonte == "BACIA DO GURGUEIA GURGUEIA"  ~ "BACIA DO GURGUEIA",
fonte == "BACIAS DIFUSAS DO BAIXO PARNAIBA Igarape"  ~ "BACIAS DIFUSAS DO BAIXO PARNAIBA",
fonte == "BACIA DO CANINDE Cabeca"  ~ "BACIA DO CANINDE",
fonte == "BACIAS DIFUSAS DO BAIXO PARNAIBA Fogo"  ~ "BACIAS DIFUSAS DO BAIXO PARNAIBA",
fonte == "BACIA DO CANINDE GAMELEIRA"  ~ "BACIA DO CANINDE",
fonte == "BACIA DO LONGA Fogo"  ~ "BACIA DO LONGA",
fonte == "BACIAS DIFUSAS DO BAIXO PARNAIBA Piaui"  ~ "BACIAS DIFUSAS DO BAIXO PARNAIBA",
fonte == "BACIA DO POTI Cabecas"  ~ "BACIA DO POTI",
fonte == "BACIA DO GURGUEIA Rio Gurgueia RIO GURGUEIA"  ~ "BACIA DO GURGUEIA",
fonte == "BACIA DO POTI ACUDE UNIAO ACUDE UNIAO"  ~ "BACIA DO POTI",                                          
fonte == "BACIA DO POTI LOTEAMENTO"  ~ "BACIA DO POTI", 
fonte == "BACIA DO LONGA Cabecas"  ~ "BACIA DO LONGA",
fonte == "BACIA DO CANINDE Pastos"  ~ "BACIA DO CANINDE",
fonte == "BACIA DO POTI Rio do Cais RIO"  ~ "BACIA DO POTI",
fonte == "BACIA DO CANINDE BAIXAO"  ~ "BACIA DO CANINDE",
fonte == "BACIA DO POTI sem nome SEM NOME"  ~ "BACIA DO POTI",                  
fonte == "BACIA DO LONGA Marataoan MARATAOAN"  ~ "BACIA DO LONGA",
fonte == "BACIA DO CANINDE Poti"  ~ "BACIA DO CANINDE",     
fonte == "BACIA DO CANINDE RIO"  ~ "BACIA DO CANINDE",  
fonte == "BACIA DO POTI Pedra de Fogo PEDRA"  ~ "BACIA DO POTI",                  
fonte == "BACIA DO POTI LAGOA"  ~ "BACIA DO POTI",                  
fonte == "BACIA DO POTI corrego Park sul CORREGO"  ~ "BACIA DO POTI",  
fonte == "BACIA DO POTI ACUDE DO CRISPIM ACUDE"  ~ "BACIA DO POTI",  
fonte == "BACIA DO POTI CURSO D"  ~ "BACIA DO POTI",
fonte == "BACIA DO POTI ACUDE DO PREFEITO ACUDE"  ~ "BACIA DO POTI",                   
fonte == "BACIA DO CANINDE RIACHO DO PEDREGULHO"  ~ "BACIA DO CANINDE",
fonte == "BACIA DO POTI Lagoa do Zoobotanico LAGOA"  ~ "BACIA DO POTI",
fonte == "BACIA DO CANINDE POCO DO MARRUA"  ~ "BACIA DO CANINDE",
fonte == "BACIA DO CANINDA"  ~ "BACIA DO CANINDE",
fonte == "BACIAS DIFUSAS DO BAIXO PARNAIBA Areado"  ~ "BACIAS DIFUSAS DO BAIXO PARNAIBA",
fonte == "BACIA DO GURGUEIA Algodoes II ALGODOES II"  ~ "BACIA DO GURGUEIA",
fonte == "BACIA DO GURGUEIA Nascente NASCENTE"  ~ "BACIA DO GURGUEIA",
fonte == "BACIA DO POTI Fogo"  ~ "BACIA DO POTI",
fonte == "BACIA DO LONGA MARATOA"  ~ "BACIA DO LONGA",
fonte == "BACIA DO CANINDE ACUDE"  ~ "BACIA DO CANINDE",
fonte == "BACIA DO LONGA Currais Novos CURRAIS NOVOS"  ~ "BACIA DO LONGA",
fonte == "BACIA DO CANINDE RIACHAO"  ~ "BACIA DO CANINDE",                      
fonte == "BACIA DO POTI Riacho"  ~ "BACIA DO POTI",
fonte == "BACIA DO CANINDE PEDRA REDONDA PEDRA REDONDA"  ~ "BACIA DO CANINDE",  
fonte == "BACIA DO CANINDE RIO MARCAL"  ~ "BACIA DO CANINDE", 
fonte == "BACIA DO POTI Sem denominacao SEM DENOMINACAO"  ~ "BACIA DO POTI",
fonte == "BACIA DO CANINDE Riacho Mimbo RIACHO MIMBO"  ~ "BACIA DO CANINDE", 
fonte == "BACIA DO CANINDE BARRAGEM DO OITI"  ~ "BACIA DO CANINDE", 
fonte == "BACIAS DIFUSAS DO LITORAL Aluvionar"  ~ "BACIAS DIFUSAS DO LITORAL", 
fonte == "BACIA DO CANINDE Cabecas"  ~ "BACIA DO CANINDE", 

    # Default case
    TRUE ~ fonte
  ))


#unique(extracted_df$fonte_principal)



```

# Save file
```{r}

write.csv(extracted_df, 
          file = "C:/Users/wb618493/OneDrive - WBG/Documents/Piaui - DPL/Cobranca de Agua/outorgas_pi_raw_15-01-2024.csv", 
          row.names = FALSE, 
          fileEncoding = "latin1")

# Confirm that the data has been written
#cat("Data has been written to", output_csv)


```

